import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { Header, WeatherCard } from '../components';
import { IWeather } from '../interface';
import fetchWeatherData from '../helpers/fetchWeatherData';
import { useContext } from 'react';
import { SearchContext } from '../context/SearchContext';


export default function Home({getWeather}:HomeProps) {
  const {data} = useContext(SearchContext);
  console.log(data);
  return (
    <div >
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className='container mx-auto'>
        <div className='grid grid-cols-2'>
          {/* <CitySearch /> */}
          <WeatherCard getWeather={getWeather} />
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const user_id = req.cookies.user_id;
  const city = req.cookies.city;
  
  if (!user_id) {
    return {
      redirect: { destination: '/auth', permanent: false }
    };
  }

  // const city = 'london';
  const datas = await fetchWeatherData(city);

  return {
    props: {
      getWeather: datas
    }
  };
};


interface HomeProps{
  getWeather:IWeather
}
